{
 "title": "cpu",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"100 * (1 - node_filesystem_avail_bytes{fstype!=\"tmpfs\"} / node_filesystem_size_bytes{fstype!=\"tmpfs\"})\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{\"100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}