{
 "title": "New dashboard Copy",
 "time": { "from": "2026-02-07T07:06:06.563Z", "to": "2026-02-07T13:06:06.563Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{\" 100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{\"100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{\"100 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)100 * (1 - node_filesystem_avail_bytes{fstype!=\"tmpfs\"} / node_filesystem_size_bytes{fstype!=\"tmpfs\"})\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{\"avg by(instance) (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}